name: Rhythmic Lingustics
favicon: null
layout_spectrum: 0.4073670054785907
typography_spectrum: 0.9399049438070506
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.4302809804212302
  lightness: 0.9786214716732502
  saturation: 0.4057901776395738
  rhythmicContrast: 0.4281423494685441
purpose: []
